apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "credit-scoring-engine.fullname" . }}-models
  labels:
    {{- include "credit-scoring-engine.labels" . | nindent 4 }}
data:
  proprietary-score-v2.3.pkl: |
