apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-credit-scoring-engine-dev
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:abc123def456789012345678901234567890123456789012345678901234567890
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config-dev
              key: SPRING_PROFILES_ACTIVE
        - name: JVM_OPTS
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config-dev
              key: JVM_OPTS
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pe-eng-credit-scoring-engine-creds-dev
              key: DATABASE_URL
        livenessProbe:
          httpGet:
            path: /api/v1/credit/health/detailed
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/v1/credit/health/detailed
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 20
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: logs-volume
          mountPath: /deployments/logs
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: logs-volume
        emptyDir: {}
