apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-creds-dev
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_WITH_ACTUAL_DATABASE_URL"
  EXPERIAN_API_URL: "REPLACE_WITH_ACTUAL_EXPERIAN_API_URL"
  EQUIFAX_API_URL: "REPLACE_WITH_ACTUAL_EQUIFAX_API_URL"
  TRANSUNION_API_URL: "REPLACE_WITH_ACTUAL_TRANSUNION_API_URL"
  INCOME_VERIFICATION_API: "REPLACE_WITH_ACTUAL_INCOME_VERIFICATION_API"
  BANK_STATEMENT_ANALYZER: "REPLACE_WITH_ACTUAL_BANK_STATEMENT_ANALYZER_API"
