apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring-engine
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: credit-scoring-engine
        resources:
          requests:
            cpu: "500m"
            memory: "1536Mi"
          limits:
            cpu: "2000m"
            memory: "3072Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
