apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credit-scoring-engine.fullname" . }}-secret
  labels:
    {{- include "credit-scoring-engine.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: ""
  api-keys: ""
  encryption-keys: ""
