apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../deployment.yaml
- ../../service.yaml
- ../../configmap.yaml

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: registry.bank.internal/credit-scoring-engine
  newTag: "3.1.0-dev@sha256:def456abc789012345678901234567890123456789012345678901234567890123"
