apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "credit-scoring-engine.fullname" . }}-config
  labels:
    {{- include "credit-scoring-engine.labels" . | nindent 4 }}
data:
  application.properties: |
{{- .Values.configMap.applicationProperties | nindent 4 }}
