apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.team }}-{{ .Values.appName }}-{{ .Values.environment }}-fluent-bit-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    environment: {{ .Values.environment }}
    managed-by: {{ .Values.managedBy }}
    helm.sh/chart: {{ include "credit-scoring-engine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /app/logs/*.log
        Parser            json
        Tag               credit-scoring.*
        Refresh_Interval  5

    [OUTPUT]
        Name  forward
        Match *
        Host  loki-gateway.observability.svc.cluster.local
        Port  3100
  
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%d %H:%M:%S.%L
