apiVersion: v1
kind: Service
metadata:
  name: {{ include "credit-scoring-engine.fullname" . }}
  labels:
    {{- include "credit-scoring-engine.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "credit-scoring-engine.selectorLabels" . | nindent 4 }}
