apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-team-credit-scoring-engine-prod-config
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: kubernetes
data:
  application.properties: |
    server.port=8080
    management.endpoints.web.exposure.include=health,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    
    logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
    logging.level.com.banking.credit=INFO
    logging.level.org.springframework=WARN
    
    spring.datasource.url=jdbc:postgresql://credit-postgres-primary:5432/creditdb
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.jpa.hibernate.ddl-auto=validate
    
    spring.redis.host=credit-redis-cluster
    spring.redis.port=6379
    spring.redis.password=${REDIS_PASSWORD}
