apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-credit-scoring-engine-config-dev
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
data:
  application.properties: |
    spring.profiles.active=production,scoring
    server.port=8080
    
    logging.level.com.banking.credit=INFO
    logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","logger":"%logger","message":"%msg"}%n
    
    management.endpoints.web.exposure.include=health,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    
    management.metrics.export.prometheus.enabled=true
    management.endpoint.prometheus.enabled=true
