---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-credit-scoring-engine-prod-config
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: helm
data:
  proprietary-score-v2.3.pkl: |
