apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-models
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: openshift
data:
  proprietary-score-v2.3.pkl: |
    MODEL_VERSION=2.3
    MODEL_TYPE=PROPRIETARY_SCORING
    FEATURE_COUNT=247
    TRAINING_DATE=2024-12-01
    VALIDATION_ACCURACY=0.94
    MODEL_CHECKSUM=sha256:placeholder
  model-config.yaml: |
    model:
      version: "2.3"
      type: "proprietary-scoring"
      features: 247
      thresholds:
        excellent: 740
        good: 670
        fair: 580
        poor: 0
      weights:
        fico: 0.7
        vantage: 0.3
