apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-credit-scoring-engine-prod
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  SPRING_PROFILES_ACTIVE: "production,scoring"
  JVM_OPTS: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
  
  EXPERIAN_API_URL: "https://api.experian.com/credit"
  EQUIFAX_API_URL: "https://api.equifax.com/ews"
  TRANSUNION_API_URL: "https://api.transunion.com/credit"
  CREDIT_API_TIMEOUT: "15000"
  
  FICO_MODEL_VERSION: "9.0"
  VANTAGE_MODEL_VERSION: "4.0"
  CUSTOM_MODEL_PATH: "/models/proprietary-score-v2.3.pkl"
  
  INCOME_VERIFICATION_API: "https://api.theworknumber.com"
  BANK_STATEMENT_ANALYZER: "https://api.plaid.com/v2"
  
  MIN_CREDIT_SCORE: "580"
  MAX_DTI_RATIO: "0.43"
  MIN_INCOME_VERIFICATION: "true"
  
  FCRA_COMPLIANCE_MODE: "true"
  ECOA_COMPLIANCE_MODE: "true"
  ADVERSE_ACTION_NOTIFICATIONS: "true"
  
  ML_FEATURE_COUNT: "247"
  MODEL_REFRESH_INTERVAL: "24h"
  A_B_TEST_ENABLED: "true"
  
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_PATTERN_CONSOLE: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%msg","mdc":%X}%n'
  SPRING_OUTPUT_ANSI_ENABLED: "never"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-ml-models-config-prod
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  proprietary-score-v2.3.pkl: |
