apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-credit-scoring-engine-prod-config
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  application.properties: |
    spring.profiles.active=production,scoring
    server.port=8080
    
    spring.datasource.url=jdbc:postgresql://credit-postgres-primary:5432/creditdb
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.format_sql=false
    
    spring.redis.host=credit-redis-cluster
    spring.redis.port=6379
    spring.redis.timeout=2000ms
    spring.redis.lettuce.pool.max-active=8
    spring.redis.lettuce.pool.max-idle=8
    spring.redis.lettuce.pool.min-idle=0
    
    management.endpoints.web.exposure.include=health,metrics,prometheus,info
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    
    logging.level.com.banking.credit=INFO
    logging.level.org.springframework.security=WARN
    logging.level.org.hibernate.SQL=WARN
    logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%replace(%msg){'[\r\n]+', ' '}","mdc":"%X"}%n
    logging.pattern.file={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%replace(%msg){'[\r\n]+', ' '}","mdc":"%X"}%n
    
    server.error.include-stacktrace=never
    server.error.include-message=never
    server.error.include-binding-errors=never
  
  experian.api.url: "https://api.experian.com/credit"
  equifax.api.url: "https://api.equifax.com/ews"
  transunion.api.url: "https://api.transunion.com/credit"
  credit.api.timeout: "15000"
  fico.model.version: "9.0"
  vantage.model.version: "4.0"
  custom.model.path: "/models/proprietary-score-v2.3.pkl"
  income.verification.api: "https://api.theworknumber.com"
  bank.statement.analyzer: "https://api.plaid.com/v2"
  min.credit.score: "580"
  max.dti.ratio: "0.43"
  min.income.verification: "true"
  fcra.compliance.mode: "true"
  ecoa.compliance.mode: "true"
  adverse.action.notifications: "true"
  ml.feature.count: "247"
  model.refresh.interval: "24h"
  ab.test.enabled: "true"
