apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-engine-config-dev
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: kubectl
data:
  application.properties: |
    server.port=8080
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    
    spring.datasource.url=jdbc:h2:mem:creditdb
    spring.datasource.driver-class-name=org.h2.Driver
    spring.h2.console.enabled=true
    
    logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
    logging.level.com.banking.credit=INFO
    logging.level.org.springframework.web=DEBUG
