---
apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-models
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  proprietary-score-v2.3.pkl: |
    MODEL_VERSION=2.3
    MODEL_TYPE=proprietary-scoring
    FEATURE_COUNT=247
