apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-credit-scoring-models-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: helm
data:
  proprietary-score-v2.3.pkl: |
    model_version: "2.3"
    model_type: "proprietary-credit-scoring"
    feature_count: 247
    last_updated: "2024-01-15T10:30:00Z"
