apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-models-config
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  model-info.txt: |
    FICO_MODEL_VERSION=9.0
    VANTAGE_MODEL_VERSION=4.0
    CUSTOM_MODEL_PATH=/models/proprietary-score-v2.3.pkl
    ML_FEATURE_COUNT=247
    MODEL_REFRESH_INTERVAL=24h
