apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-models
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  model-config.properties: |
    model.version=2.3
    model.type=proprietary-score
    model.path=/models/proprietary-score-v2.3.pkl
