apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-models
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  proprietary-score-v2.3.pkl: |
  application.properties: |
    server.port=8080
    management.endpoints.web.exposure.include=health,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    management.metrics.export.prometheus.enabled=true
    
    logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%msg","mdc":"%X"}%n
    logging.level.com.banking.credit=INFO
    logging.level.org.springframework=WARN
    logging.level.org.apache.http=WARN
    
    spring.datasource.url=jdbc:h2:mem:creditdb
    spring.datasource.driver-class-name=org.h2.Driver
    spring.jpa.hibernate.ddl-auto=create-drop
    spring.jpa.show-sql=false
    
    spring.redis.host=credit-redis-cluster
    spring.redis.port=6379
    spring.redis.timeout=2000ms
