---
apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-models
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  proprietary-score-v2.3.pkl: |
    model_version: "2.3"
    feature_count: 247
    model_type: "gradient_boosting"
