apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-credit-scoring-config
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: production
    managed-by: helm
data:
  application-production.properties: |
    spring.datasource.url=jdbc:postgresql://credit-postgres-primary:5432/creditdb
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.datasource.driver-class-name=org.postgresql.Driver

    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.show-sql=false

    spring.redis.host=credit-redis-cluster
    spring.redis.port=6379
    spring.redis.password=${REDIS_PASSWORD}

    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    management.metrics.export.prometheus.enabled=true
