apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-models-config
  namespace: pe-eng-credit-scoring-dev
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
data:
  proprietary-score-v2.3.pkl: |
    model_version: "2.3"
    feature_count: 247
