apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-team-credit-scoring-engine-config-prod
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: helm
data:
  application.properties: |
    server.port=8080
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    
    logging.level.com.banking.credit=INFO
    logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%msg"}%n
    logging.pattern.file={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%msg"}%n
    
    spring.datasource.url=jdbc:postgresql://credit-postgres-primary:5432/creditdb
    spring.datasource.username=${DB_USERNAME:credituser}
    spring.datasource.password=${DB_PASSWORD:creditpass}
    
    spring.redis.host=credit-redis-cluster
    spring.redis.port=6379
    
    credit.scoring.timeout=15000
    credit.scoring.max-retries=3
    credit.scoring.circuit-breaker.enabled=true
  proprietary-score-v2.3.pkl: |
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-team-credit-scoring-engine-fluent-bit-config-prod
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: helm
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*credit-scoring-engine*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name  forward
        Match *
        Host  loki-gateway.openshift-logging.svc.cluster.local
        Port  24224
  
  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
