apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-credit-scoring-engine-dev
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: openshift
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: dev
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:placeholder
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "500m"
            memory: "1843Mi"
          limits:
            cpu: "2000m"
            memory: "3072Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-engine-config
              key: SPRING_PROFILES_ACTIVE
        - name: JVM_OPTS
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-engine-config
              key: JVM_OPTS
        envFrom:
        - configMapRef:
            name: credit-scoring-engine-config
        - secretRef:
            name: credit-scoring-engine-creds
        livenessProbe:
          httpGet:
            path: /actuator/health/detailed
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/detailed
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 20
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: models-volume
          mountPath: /models
          readOnly: true
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: models-volume
        configMap:
          name: ml-models-config
