apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: helm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "500m"
            memory: "1536Mi"
          limits:
            cpu: "2000m"
            memory: "3072Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JBP_CONFIG_OPEN_JDK_JRE
          value: '[jre: {version: 17.+}]'
        - name: JVM_OPTS
          value: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
        envFrom:
        - secretRef:
            name: credit-scoring-engine-secrets-prod
        - configMapRef:
            name: credit-scoring-engine-config-prod
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 1
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: models-volume
          mountPath: /models
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: models-volume
        persistentVolumeClaim:
          claimName: credit-scoring-models-pvc
