apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-team-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: helm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fluent-bit
        image: registry.bank.internal/fluent-bit:2.1.0@sha256:7d865e959b2466166c2ea2c497ec7c319aec0e43f6ac2e7d32ae5ef9e5e4b5a3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "500m"
            memory: "1536Mi"
          limits:
            cpu: "2000m"
            memory: "3072Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JBP_CONFIG_OPEN_JDK_JRE
          value: '[jre: {version: 17.+}]'
        - name: JVM_OPTS
          value: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
        - name: EXPERIAN_API_URL
          value: "https://api.experian.com/credit"
        - name: EQUIFAX_API_URL
          value: "https://api.equifax.com/ews"
        - name: TRANSUNION_API_URL
          value: "https://api.transunion.com/credit"
        - name: CREDIT_API_TIMEOUT
          value: "15000"
        - name: FICO_MODEL_VERSION
          value: "9.0"
        - name: VANTAGE_MODEL_VERSION
          value: "4.0"
        - name: CUSTOM_MODEL_PATH
          value: "/models/proprietary-score-v2.3.pkl"
        - name: INCOME_VERIFICATION_API
          value: "https://api.theworknumber.com"
        - name: BANK_STATEMENT_ANALYZER
          value: "https://api.plaid.com/v2"
        - name: MIN_CREDIT_SCORE
          value: "580"
        - name: MAX_DTI_RATIO
          value: "0.43"
        - name: MIN_INCOME_VERIFICATION
          value: "true"
        - name: FCRA_COMPLIANCE_MODE
          value: "true"
        - name: ECOA_COMPLIANCE_MODE
          value: "true"
        - name: ADVERSE_ACTION_NOTIFICATIONS
          value: "true"
        - name: ML_FEATURE_COUNT
          value: "247"
        - name: MODEL_REFRESH_INTERVAL
          value: "24h"
        - name: A_B_TEST_ENABLED
          value: "true"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: models-volume
          mountPath: /models
          readOnly: true
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: models-volume
        configMap:
          name: banking-team-ml-models-config-prod
      - name: fluent-bit-config
        configMap:
          name: banking-team-fluent-bit-config-prod
