apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: openshift
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: openshift
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:7d865e959b2466f8239fcba23c8966c8c1eabd319d8e4f30fe9f8eba5c2b4b5d
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "600m"
            memory: "1843Mi"
          limits:
            cpu: "1000m"
            memory: "3072Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JBP_CONFIG_OPEN_JDK_JRE
          value: '[jre: {version: 17.+}]'
        - name: JVM_OPTS
          value: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
        - name: EXPERIAN_API_URL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: EXPERIAN_API_URL
        - name: EQUIFAX_API_URL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: EQUIFAX_API_URL
        - name: TRANSUNION_API_URL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: TRANSUNION_API_URL
        - name: CREDIT_API_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: CREDIT_API_TIMEOUT
        - name: FICO_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: FICO_MODEL_VERSION
        - name: VANTAGE_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: VANTAGE_MODEL_VERSION
        - name: CUSTOM_MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: CUSTOM_MODEL_PATH
        - name: INCOME_VERIFICATION_API
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: INCOME_VERIFICATION_API
        - name: BANK_STATEMENT_ANALYZER
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: BANK_STATEMENT_ANALYZER
        - name: MIN_CREDIT_SCORE
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: MIN_CREDIT_SCORE
        - name: MAX_DTI_RATIO
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: MAX_DTI_RATIO
        - name: MIN_INCOME_VERIFICATION
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: MIN_INCOME_VERIFICATION
        - name: FCRA_COMPLIANCE_MODE
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: FCRA_COMPLIANCE_MODE
        - name: ECOA_COMPLIANCE_MODE
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: ECOA_COMPLIANCE_MODE
        - name: ADVERSE_ACTION_NOTIFICATIONS
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: ADVERSE_ACTION_NOTIFICATIONS
        - name: ML_FEATURE_COUNT
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: ML_FEATURE_COUNT
        - name: MODEL_REFRESH_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: MODEL_REFRESH_INTERVAL
        - name: A_B_TEST_ENABLED
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-prod-config
              key: A_B_TEST_ENABLED
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: models-volume
          mountPath: /models
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: models-volume
        emptyDir: {}
      - name: logs-volume
        emptyDir: {}
