apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-eng-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: kubernetes
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: kubernetes
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:abc123def456789012345678901234567890123456789012345678901234567890
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "3Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JVM_OPTS
          value: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
        - name: EXPERIAN_API_URL
          value: "https://api.experian.com/credit"
        - name: EQUIFAX_API_URL
          value: "https://api.equifax.com/ews"
        - name: TRANSUNION_API_URL
          value: "https://api.transunion.com/credit"
        - name: CREDIT_API_TIMEOUT
          value: "15000"
        - name: FICO_MODEL_VERSION
          value: "9.0"
        - name: VANTAGE_MODEL_VERSION
          value: "4.0"
        - name: FCRA_COMPLIANCE_MODE
          value: "true"
        - name: ECOA_COMPLIANCE_MODE
          value: "true"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: logs-volume
          mountPath: /app/logs
      - name: fluent-bit
        image: registry.bank.internal/fluent-bit:2.1.0@sha256:def456789012345678901234567890123456789012345678901234567890123456
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: logs-volume
          mountPath: /app/logs
          readOnly: true
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: logs-volume
        emptyDir: {}
      - name: fluent-bit-config
        configMap:
          name: banking-eng-fluent-bit-config-prod
