apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-credit-scoring-engine-prod
  namespace: banking-platform-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: helm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:abc123def456789012345678901234567890123456789012345678901234567890
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "500m"
            memory: "1536Mi"
          limits:
            cpu: "2000m"
            memory: "3072Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JBP_CONFIG_OPEN_JDK_JRE
          value: '[jre: {version: 17.+}]'
        - name: JVM_OPTS
          value: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
        - name: EXPERIAN_API_URL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: experian-api-url
        - name: EQUIFAX_API_URL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: equifax-api-url
        - name: TRANSUNION_API_URL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: transunion-api-url
        - name: CREDIT_API_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: credit-api-timeout
        - name: FICO_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: fico-model-version
        - name: VANTAGE_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: vantage-model-version
        - name: CUSTOM_MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: custom-model-path
        - name: INCOME_VERIFICATION_API
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: income-verification-api
        - name: BANK_STATEMENT_ANALYZER
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: bank-statement-analyzer
        - name: MIN_CREDIT_SCORE
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: min-credit-score
        - name: MAX_DTI_RATIO
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: max-dti-ratio
        - name: MIN_INCOME_VERIFICATION
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: min-income-verification
        - name: FCRA_COMPLIANCE_MODE
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: fcra-compliance-mode
        - name: ECOA_COMPLIANCE_MODE
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: ecoa-compliance-mode
        - name: ADVERSE_ACTION_NOTIFICATIONS
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: adverse-action-notifications
        - name: ML_FEATURE_COUNT
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: ml-feature-count
        - name: MODEL_REFRESH_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: model-refresh-interval
        - name: A_B_TEST_ENABLED
          valueFrom:
            configMapKeyRef:
              name: pe-eng-credit-scoring-engine-config
              key: a-b-test-enabled
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 1
          periodSeconds: 10
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: models-volume
          mountPath: /models
          readOnly: true
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: models-volume
        configMap:
          name: ml-models-config
