apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-credit-scoring-engine-prod
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: kubernetes
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      app.kubernetes.io/part-of: retail-banking
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: kubernetes
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:7d865e959b2466f8239fcba1a2b6b0e729e235fb2b2c3a8b8a5c9f1e4d6c8a2b
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JBP_CONFIG_OPEN_JDK_JRE
          value: '[jre: {version: 17.+}]'
        - name: JVM_OPTS
          value: "-Xmx1536m -XX:+UseG1GC -XX:+UseStringDeduplication"
        - name: EXPERIAN_API_URL
          value: "https://api.experian.com/credit"
        - name: EQUIFAX_API_URL
          value: "https://api.equifax.com/ews"
        - name: TRANSUNION_API_URL
          value: "https://api.transunion.com/credit"
        - name: CREDIT_API_TIMEOUT
          value: "15000"
        - name: FICO_MODEL_VERSION
          value: "9.0"
        - name: VANTAGE_MODEL_VERSION
          value: "4.0"
        - name: CUSTOM_MODEL_PATH
          value: "/models/proprietary-score-v2.3.pkl"
        - name: INCOME_VERIFICATION_API
          value: "https://api.theworknumber.com"
        - name: BANK_STATEMENT_ANALYZER
          value: "https://api.plaid.com/v2"
        - name: MIN_CREDIT_SCORE
          value: "580"
        - name: MAX_DTI_RATIO
          value: "0.43"
        - name: MIN_INCOME_VERIFICATION
          value: "true"
        - name: FCRA_COMPLIANCE_MODE
          value: "true"
        - name: ECOA_COMPLIANCE_MODE
          value: "true"
        - name: ADVERSE_ACTION_NOTIFICATIONS
          value: "true"
        - name: ML_FEATURE_COUNT
          value: "247"
        - name: MODEL_REFRESH_INTERVAL
          value: "24h"
        - name: A_B_TEST_ENABLED
          value: "true"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: logs-volume
          mountPath: /app/logs
      - name: fluent-bit
        image: registry.bank.internal/fluent-bit:2.1.0@sha256:9f8e7d6c5b4a3928374650192837465019283746501928374650192837465019
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: logs-volume
        emptyDir: {}
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
