apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: helm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:abc123def456789012345678901234567890123456789012345678901234567890
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JBP_CONFIG_OPEN_JDK_JRE
          value: '[jre: {version: 17.+}]'
        - name: JVM_OPTS
          value: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
        - name: EXPERIAN_API_URL
          value: "https://api.experian.com/credit"
        - name: EQUIFAX_API_URL
          value: "https://api.equifax.com/ews"
        - name: TRANSUNION_API_URL
          value: "https://api.transunion.com/credit"
        - name: CREDIT_API_TIMEOUT
          value: "15000"
        - name: FICO_MODEL_VERSION
          value: "9.0"
        - name: VANTAGE_MODEL_VERSION
          value: "4.0"
        - name: CUSTOM_MODEL_PATH
          value: "/models/proprietary-score-v2.3.pkl"
        - name: INCOME_VERIFICATION_API
          value: "https://api.theworknumber.com"
        - name: BANK_STATEMENT_ANALYZER
          value: "https://api.plaid.com/v2"
        - name: MIN_CREDIT_SCORE
          value: "580"
        - name: MAX_DTI_RATIO
          value: "0.43"
        - name: MIN_INCOME_VERIFICATION
          value: "true"
        - name: FCRA_COMPLIANCE_MODE
          value: "true"
        - name: ECOA_COMPLIANCE_MODE
          value: "true"
        - name: ADVERSE_ACTION_NOTIFICATIONS
          value: "true"
        - name: ML_FEATURE_COUNT
          value: "247"
        - name: MODEL_REFRESH_INTERVAL
          value: "24h"
        - name: A_B_TEST_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "500m"
            memory: "1536Mi"
          limits:
            cpu: "2000m"
            memory: "3072Mi"
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 1
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: models-volume
          mountPath: /models
        - name: app-logs
          mountPath: /var/log/app
        - name: config-volume
          mountPath: /app/config
      - name: fluent-bit
        image: registry.bank.internal/fluent-bit:2.1.0@sha256:def456789012345678901234567890123456789012345678901234567890123456
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: app-logs
          mountPath: /var/log/app
          readOnly: true
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: models-volume
        emptyDir: {}
      - name: app-logs
        emptyDir: {}
      - name: config-volume
        configMap:
          name: pe-eng-credit-scoring-engine-prod-config
      - name: fluent-bit-config
        configMap:
          name: pe-eng-credit-scoring-engine-prod-fluent-bit-config
