apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: credit-scoring-engine
        app.kubernetes.io/version: "3.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: helm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credit-scoring-engine
        image: registry.bank.internal/credit-scoring-engine:3.1.0@sha256:abc123def456789012345678901234567890123456789012345678901234567890
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "3Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production,scoring"
        - name: JVM_OPTS
          value: "-Xmx2560m -XX:+UseG1GC -XX:+UseStringDeduplication"
        - name: EXPERIAN_API_URL
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: experian-api-url
        - name: EQUIFAX_API_URL
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: equifax-api-url
        - name: TRANSUNION_API_URL
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: transunion-api-url
        - name: CREDIT_API_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: credit-api-timeout
        - name: FICO_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: fico-model-version
        - name: VANTAGE_MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: vantage-model-version
        - name: CUSTOM_MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: custom-model-path
        - name: INCOME_VERIFICATION_API
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: income-verification-api
        - name: BANK_STATEMENT_ANALYZER
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: bank-statement-analyzer
        - name: MIN_CREDIT_SCORE
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: min-credit-score
        - name: MAX_DTI_RATIO
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: max-dti-ratio
        - name: MIN_INCOME_VERIFICATION
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: min-income-verification
        - name: FCRA_COMPLIANCE_MODE
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: fcra-compliance-mode
        - name: ECOA_COMPLIANCE_MODE
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: ecoa-compliance-mode
        - name: ADVERSE_ACTION_NOTIFICATIONS
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: adverse-action-notifications
        - name: ML_FEATURE_COUNT
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: ml-feature-count
        - name: MODEL_REFRESH_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: model-refresh-interval
        - name: A_B_TEST_ENABLED
          valueFrom:
            configMapKeyRef:
              name: credit-scoring-config
              key: ab-test-enabled
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: models-volume
          mountPath: /models
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
      - name: fluent-bit
        image: registry.bank.internal/fluent-bit:2.1.0@sha256:def456789012345678901234567890123456789012345678901234567890123456
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
          readOnly: true
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: logs-volume
        emptyDir: {}
      - name: models-volume
        configMap:
          name: ml-models-config
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
