apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-eng-fluent-bit-config-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: kubernetes
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /app/logs/*.log
        Parser            json
        Tag               credit-scoring-engine.prod
        Refresh_Interval  5

    [OUTPUT]
        Name  loki
        Match *
        Host  loki.internal.banking.com
        Port  3100
        Labels job=credit-scoring-engine, environment=prod
        Label_keys $app_name,$environment
        Remove_keys time
        Line_format json

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
