---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: credit-scoring-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              forward
        Listen            0.0.0.0
        Port              24224
        Buffer_Chunk_Size 1M
        Buffer_Max_Size   6M

    [FILTER]
        Name                parser
        Match               *
        Key_Name            log
        Parser              json
        Reserve_Data        On

    [OUTPUT]
        Name  http
        Match *
        Host  loki-gateway.openshift-logging.svc.cluster.local
        Port  3100
        URI   /loki/api/v1/push
        Format json
        Json_date_key timestamp
        Json_date_format iso8601
        Header Content-Type application/json

  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key timestamp
        Time_Format %Y-%m-%d %H:%M:%S.%L
        Time_Keep   On
