apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-credit-scoring-engine-fluent-bit-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /tmp/*.log
        Parser            json
        Tag               credit-scoring-engine
        Refresh_Interval  5

    [OUTPUT]
        Name  forward
        Match *
        Host  loki-gateway.openshift-logging.svc.cluster.local
        Port  24224
        
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
