apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: kubernetes
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /var/log/app/*.log
        Parser            json
        Tag               app.logs
        Refresh_Interval  5

    [OUTPUT]
        Name  forward
        Match *
        Host  loki-gateway.openshift-logging.svc.cluster.local
        Port  24224
        
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-sidecar-prod
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/version: "2.1.0"
        app.kubernetes.io/part-of: banking-platform
        environment: prod
        managed-by: kubernetes
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fluent-bit
        image: registry.bank.internal/fluent-bit:2.1.0@sha256:placeholder
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: app-logs
          mountPath: /var/log/app
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config-prod
      - name: app-logs
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
