apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pe-eng-fluent-bit-prod
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      environment: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/version: "2.1.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        managed-by: kubernetes
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fluent-bit
        image: registry.bank.internal/fluent-bit:2.1.0
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: tmp-volume
        emptyDir: {}
