apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pe-eng-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: openshift
  annotations:
    kubernetes.io/ingress.class: "openshift-default"
    route.openshift.io/termination: "edge"
spec:
  rules:
  - host: credit-scoring.internal.banking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pe-eng-credit-scoring-engine-prod
            port:
              number: 8080
  - host: credit-api-v3.banking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pe-eng-credit-scoring-engine-prod
            port:
              number: 8080
