apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-banking-prod

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
- fluent-bit-config.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: credit-scoring-engine
  app.kubernetes.io/part-of: retail-banking
  environment: prod
  managed-by: helm
