apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/name: credit-scoring-engine
  app.kubernetes.io/part-of: retail-banking
  environment: prod
  managed-by: helm

namePrefix: credit-scoring-engine-prod-

images:
- name: registry.bank.internal/credit-scoring-engine
  newTag: "3.1.0"
