---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: credit-scoring

metadata:
  name: credit-scoring-engine
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: credit-scoring-engine
  app.kubernetes.io/version: "3.1.0"
  app.kubernetes.io/part-of: retail-banking
  environment: prod
  managed-by: helm

images:
- name: registry.bank.internal/credit-scoring-engine
  newTag: "3.1.0"
