apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pe-eng-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: kubernetes

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: credit-scoring-engine
  app.kubernetes.io/version: "3.1.0"
  app.kubernetes.io/part-of: banking-platform
  environment: prod
  managed-by: kubernetes
