apiVersion: v1
kind: Namespace
metadata:
  name: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    managed-by: kubernetes
