apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: credit-scoring-engine-netpol-dev
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
      environment: dev
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: banking-platform
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: banking-platform
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
