apiVersion: v1
kind: Secret
metadata:
  name: banking-credit-scoring-secrets
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: production
    managed-by: helm
type: Opaque
data:
  DB_USERNAME: ""  # Base64 encoded database username - populate via secret management
  DB_PASSWORD: ""  # Base64 encoded database password - populate via secret management  
  REDIS_PASSWORD: ""  # Base64 encoded Redis password - populate via secret management
