apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-prod-secrets
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
type: Opaque
data:
  DB_USERNAME: <BASE64_ENCODED_DB_USERNAME>
  DB_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>
  REDIS_PASSWORD: <BASE64_ENCODED_REDIS_PASSWORD>
