apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-secrets-prod
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: openshift
type: Opaque
data:
  database-password: ""
  redis-password: ""
  api-keys: ""
