apiVersion: v1
kind: Secret
metadata:
  name: credit-scoring-db-secret
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
type: Opaque
data:
  username: Y3JlZGl0X3VzZXI=
  password: Y3JlZGl0X3Bhc3N3b3Jk
