apiVersion: v1
kind: Secret
metadata:
  name: credit-scoring-engine-creds
stringData:
  DATABASE_URL: "jdbc:postgresql://credit-postgres-primary:5432/creditdb"
  DATABASE_USERNAME: "credit_user"
  DATABASE_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
  
  REDIS_URL: "redis://credit-redis-cluster:6379"
  REDIS_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
  
  EXPERIAN_API_KEY: "REPLACE_WITH_ACTUAL_KEY"
  EQUIFAX_API_KEY: "REPLACE_WITH_ACTUAL_KEY"
  TRANSUNION_API_KEY: "REPLACE_WITH_ACTUAL_KEY"
  
  WORK_NUMBER_API_KEY: "REPLACE_WITH_ACTUAL_KEY"
  PLAID_CLIENT_ID: "REPLACE_WITH_ACTUAL_ID"
  PLAID_SECRET: "REPLACE_WITH_ACTUAL_SECRET"
  
  ENCRYPTION_KEY: "REPLACE_WITH_ACTUAL_ENCRYPTION_KEY"
  
  KAFKA_BOOTSTRAP_SERVERS: "audit-trail-kafka:9092"
  KAFKA_USERNAME: "credit_audit_user"
  KAFKA_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
