apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-prod-secrets
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: helm
type: Opaque
data:
  DB_USERNAME: Y3JlZGl0X3VzZXI=  # credit_user (base64 encoded)
  DB_PASSWORD: Y3JlZGl0X3Bhc3M=  # credit_pass (base64 encoded)
