apiVersion: v1
kind: Secret
metadata:
  name: credit-scoring-secrets
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: openshift
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BjcmVkaXQtcG9zdGdyZXMtcHJpbWFyeTo1NDMyL2NyZWRpdGRi
  DATABASE_USERNAME: Y3JlZGl0X3VzZXI=
  DATABASE_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk
  
  REDIS_URL: cmVkaXM6Ly9jcmVkaXQtcmVkaXMtY2x1c3Rlcjo2Mzc5
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3M=
  
  EXPERIAN_API_KEY: ZXhwZXJpYW5fYXBpX2tleV9wbGFjZWhvbGRlcg==
  EQUIFAX_API_KEY: ZXF1aWZheF9hcGlfa2V5X3BsYWNlaG9sZGVy
  TRANSUNION_API_KEY: dHJhbnN1bmlvbl9hcGlfa2V5X3BsYWNlaG9sZGVy
  
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfcGxhY2Vob2xkZXI=
  JWT_SECRET: and0X3NlY3JldF9wbGFjZWhvbGRlcg==
