apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: credit-scoring-engine
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: credit-scoring-engine
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
