apiVersion: v1
kind: Service
metadata:
  name: credit-scoring-engine
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: credit-scoring-engine
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
