apiVersion: v1
kind: Service
metadata:
  name: credit-scoring-engine-service
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: banking-platform
    environment: prod
    managed-by: kubernetes
spec:
  selector:
    app.kubernetes.io/name: credit-scoring-engine
    environment: prod
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
