apiVersion: v1
kind: Service
metadata:
  name: pe-eng-credit-scoring-engine-prod
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: openshift
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: credit-scoring-tls
spec:
  selector:
    app.kubernetes.io/name: credit-scoring-engine
    environment: prod
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
