replicaCount: 4

image:
  repository: registry.bank.internal/credit-scoring-engine
  pullPolicy: IfNotPresent
  tag: "3.1.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/actuator/prometheus"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 500m
    memory: 1536Mi
  limits:
    cpu: 2000m
    memory: 3072Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 1

autoscaling:
  enabled: false
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

app:
  environment: prod
  partOf: retail-banking
  managedBy: helm
  
  creditBureau:
    experian:
      url: "https://api.experian.com/credit"
    equifax:
      url: "https://api.equifax.com/ews"
    transunion:
      url: "https://api.transunion.com/credit"
    timeout: 15000
  
  models:
    fico:
      version: "9.0"
    vantage:
      version: "4.0"
    custom:
      path: "/models/proprietary-score-v2.3.pkl"
  
  risk:
    minCreditScore: 580
    maxDtiRatio: 0.43
    minIncomeVerification: true
  
  compliance:
    fcra:
      enabled: true
    ecoa:
      enabled: true
    adverseAction:
      enabled: true
  
  ml:
    featureCount: 247
    modelRefreshInterval: "24h"
    abTestEnabled: true
