apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-credit-bureau-proxy-secret
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
type: Opaque
data:
  api-key: BASE64_ENCODED_API_KEY_PLACEHOLDER
  client-secret: BASE64_ENCODED_CLIENT_SECRET_PLACEHOLDER
