apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-encryption-service-secret
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
type: Opaque
data:
  encryption-key: BASE64_ENCODED_ENCRYPTION_KEY_PLACEHOLDER
  signing-key: BASE64_ENCODED_SIGNING_KEY_PLACEHOLDER
