apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-model-storage-s3-secret
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
type: Opaque
data:
  access-key-id: BASE64_ENCODED_ACCESS_KEY_ID_PLACEHOLDER
  secret-access-key: BASE64_ENCODED_SECRET_ACCESS_KEY_PLACEHOLDER
