apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-credit-scoring-engine-redis-cluster-secret
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
type: Opaque
data:
  password: BASE64_ENCODED_PASSWORD_PLACEHOLDER
  auth-token: BASE64_ENCODED_AUTH_TOKEN_PLACEHOLDER
