replicaCount: 2

environment: test

app:
  name: credit-scoring-engine
  version: "3.1.0"
  partOf: retail-banking

resources:
  requests:
    cpu: "250m"
    memory: "768Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"

ingress:
  enabled: true
  hosts:
    - host: credit-scoring-test.internal.banking.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: credit-scoring-test-tls
      hosts:
        - credit-scoring-test.internal.banking.com

env:
  SPRING_PROFILES_ACTIVE: "test,scoring"
  JVM_OPTS: "-Xmx768m -XX:+UseG1GC -XX:+UseStringDeduplication"

configMap:
  applicationProperties: |
    spring.datasource.url=jdbc:postgresql://credit-postgres-test:5432/creditdb_test
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.show-sql=false
    
    spring.redis.host=credit-redis-test
    spring.redis.port=6379
    spring.redis.password=${REDIS_PASSWORD}
    
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.probes.enabled=true
    
    logging.level.com.banking.credit=INFO
    logging.level.org.springframework=WARN
    logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}","level":"%level","logger":"%logger{36}","thread":"%thread","message":"%msg"}%n
