replicaCount: 2

image:
  repository: registry.bank.internal/credit-scoring-engine
  tag: "3.1.0-dev"
  digest: "sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730"

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 600m
    memory: 1536Mi

labels:
  environment: dev

env:
  SPRING_PROFILES_ACTIVE: "development,scoring"
  MIN_CREDIT_SCORE: "500"
  A_B_TEST_ENABLED: "false"

autoscaling:
  enabled: false
