apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-scoring-config
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    managed-by: kustomize
data:
  EXPERIAN_API_URL: "https://api.experian.com/credit"
  EQUIFAX_API_URL: "https://api.equifax.com/ews"
  TRANSUNION_API_URL: "https://api.transunion.com/credit"
  CREDIT_API_TIMEOUT: "15000"
  
  FICO_MODEL_VERSION: "9.0"
  VANTAGE_MODEL_VERSION: "4.0"
  CUSTOM_MODEL_PATH: "/models/proprietary-score-v2.3.pkl"
  
  INCOME_VERIFICATION_API: "https://api.theworknumber.com"
  BANK_STATEMENT_ANALYZER: "https://api.plaid.com/v2"
  
  MIN_CREDIT_SCORE: "580"
  MAX_DTI_RATIO: "0.43"
  MIN_INCOME_VERIFICATION: "true"
  
  FCRA_COMPLIANCE_MODE: "true"
  ECOA_COMPLIANCE_MODE: "true"
  ADVERSE_ACTION_NOTIFICATIONS: "true"
  
  ML_FEATURE_COUNT: "247"
  MODEL_REFRESH_INTERVAL: "24h"
  A_B_TEST_ENABLED: "true"
