apiVersion: v1
kind: ServiceAccount
metadata:
  name: credit-scoring-engine-sa
  namespace: credit-scoring
  labels:
    app.kubernetes.io/name: credit-scoring-engine
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/part-of: retail-banking
    environment: dev
    managed-by: helm
automountServiceAccountToken: false
