apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-scoring-engine
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: credit-scoring-engine
        resources:
          requests:
            cpu: "250m"
            memory: "768Mi"
          limits:
            cpu: "1000m"
            memory: "1536Mi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev,scoring"
